Repository Nadeen123/emarket, pull requests merged in 2019-09, with the labels that each got.

#14 Refactor_NavBar related to #3
  client/src/components/Navbar/index.js
Labels: Priority1, Refactor, Waiting review, bug

#20 Refactor console.log related to #19
  client/src/components/cart_page/index.js
  src/controller/getCartProdusts.js
Labels: Refactor, bug, done

#15 Naming convention in files related to # 4
  client/src/components/About_us/index.js
  client/src/components/About_us/style.css
  client/src/components/App/App.js
  client/src/components/Cart_page/index.js
  client/src/components/Cart_page/style.css
  client/src/components/Product_page/Product_info/index.js
  client/src/components/Product_page/Product_info/style.css
  client/src/components/Product_page/index.js
  client/src/components/Register/index.js
  client/src/components/Register/style.css
  client/src/components/Shipping_info/index.js
  client/src/components/Shipping_info/style.css
  src/controller/delete_item.js
  src/controller/getProducts.js
  src/controller/get_cart_products.js
  src/controller/get_category_products.js
  src/controller/get_products.js
  src/controller/index.js
  src/database/queries/delete_item.js
  src/database/queries/get_all_product.js
  src/database/queries/get_cart_products.js
Labels: Priority2, Refactor, bug, done

#22 Comments
  client/src/components/App/App.js
  client/src/components/Navbar/index.js
  client/src/components/Product_page/index.js
  client/src/components/Register/index.js
  client/src/components/Search_bar/index.js
  client/src/components/Shipping_info/index.js
  client/src/components/Shop/index.js
  src/middleware/error.js
Labels: Refactor, documentation, done
